### ISSUE TITLE
Stream to Chromecast doesn't support certain chromecast names

### ISSUE THREAD

**Issue by GHowlett** [PopcornTime-CE/desktop#102]
When selecting the chromecast watch option and attempting to stream the media immediately starts playing within the popcorntime window instead of streaming when the target chromecast's name contains certain characters. When the name only contains spaces and letter characters there is no problem and the video immediately starts streaming. However when I rename the chromecast to contain an apostrophe this issue persists.

Chromecast hardware: gen 1
Chromecast firmware: 1.20.66189

**Comment by captainyarr** [comment]
What names have you tested with?

**Comment by YIFYtorrents** [comment]
we could maybe use replace function for title string

EDIT: I have tried names with apostrophe and it works. I think the last update 4.1-5 has fixed this issue.
