### ISSUE TITLE
Favorite / bookmark 

### ISSUE THREAD

**Issue by raphcool12** [PopcornTime-CE/desktop#11]
Hi I notice a bug when we add alot of movie or tv series to bookmark/ Favorite its made the bookmark apps crash the favorite seem to be there because there is no message no favorite found if I restart popcorn time everthing work well but If I clic on the heart there is still nothing in the section but If I search for the movie I Bookmark earlier the red heart is still there So its sems that when youve alot of movie bookmarked its cause an issue with bookmark section the only way I found to get it back its to clear favorite in the setting so by doing that I can bookmark again bat after a few there is nothing and its crash again it's look like all become invisible

 im connected to trackt and my tv show account :p 

Keep up your amazing works :)

raphcool12

**Comment by YIFYtorrents** [comment]
I just bookmarked 55 movies and I didn't see any problems.

Did you install from source or from binary at [http://popcorntime.ag](popcorntime.ag) ?

**Comment by raphcool12** [comment]
yes :P I haven try today an after a few add some movie or tv become invisible when I check back to my list I use Yts.Ag has movie Provider Do you think it could be relatd to the issue? i'm also connected to my tv acount and Trackt I also Try to réinstalle without sucess 

you work is Amazing :)

I wait for your news :)

**Comment by YIFYtorrents** [comment]
## Warning

You can switch to yts.ag but keep in mind that most of the new features are only compatible with the new YIFY.is API. Switching to yts.ag is not yet recommended therefore.

**yts.ag API #missingFeatures**
- google cloud player
- cast & director info
- provider control
- sorting by views
- sorting by year & last added
- no XML support
- full list of new features >> https://github.com/PopcornTime-CE/desktop/blob/master/CHANGELOG.md

**YIFY.is API #bugs**
- missing runtime info on new releases (coming soon)
- missing background image on new releases (coming soon)
- peers are not up to date (doesn't affect streaming experience)

Source: https://www.reddit.com/r/PopcornTimeCE/comments/3ynqyd/switching_to_ytsag_api_with_gui_newfeature_bugfix/

**Comment by raphcool12** [comment]
ok thanks for the advice But I just try to switch to .is and having the same probem :( but I have another question do you have the intention to put the new features on YTS.ag too?

**Comment by YIFYtorrents** [comment]
We just grab the movie content from them. Better ask yts.ag if they are going to add new features to their API. We tread all APIs equally and fairly, but we are not in control of yts.ag or yify.is API features.

**Comment by raphcool12** [comment]
ok so what you said It's you that correct api bug ? or adding New feature its the person who get the site?

sorry for my english :)

**Comment by YIFYtorrents** [comment]
Sorry, I don't understand your question!

**Comment by raphcool12** [comment]
you and your team add new features to YTS.is api right? are you the one a create the YTS.Is site or just a member of the popcorn team? Because on the .is site there is a link talk about your popcorn version

so the new features on version 0.3.9 is that made by the popcorn Team or the leader of YTS website?

**Comment by raphcool12** [comment]
after other test i reinstall Popcorn Time and clear The data base at the same time The bookmarks problems Seems to came when we put the YTS.ag API my question is the you plan to fix thant on the next version?

**Comment by YIFYtorrents** [comment]
I am trying to fix it, thanks.

**Comment by raphcool12** [comment]
ok thanks you rock sorry again for my bad English :)

**Comment by raphcool12** [comment]
can I close the issue or should wait until you fix the problem?

**Comment by YIFYtorrents** [comment]
Better wait until we fix the problem!

**Comment by raphcool12** [comment]
ok thanks :) im new user so I don't really know who you deal with issue

**Comment by YIFYtorrents** [comment]
it's fixed with the new v0.4.0-2

**Comment by raphcool12** [comment]
ok thanks again :P
