### ISSUE TITLE
trakt.tv login not woring

### ISSUE THREAD

**Issue by ksetlak** [PopcornTime-CE/desktop#110]
After clicking the login button for trakt.tv in settings the login window appears and then immediately disappears. Console output attached.
[ptime_error.txt](https://github.com/PopcornTimeCommunity/desktop/files/586508/ptime_error.txt)

**Comment by YIFYtorrents** [comment]
please update your popcorn time to v0.4.1-5 and see if the issue still ocurs.

**Comment by ksetlak** [comment]
Working, thxOn 29 Dec 2016 4:57 p.m., smiley <notifications@github.com> wrote:please update your popcorn time to v0.4.1-5

**Comment by YIFYtorrents** [comment]
for some reason, trakt.tv does not work for me: https://github.com/PopcornTimeCommunity/desktop/issues/119

**Comment by captainyarr** [comment]
Check #127 for fix
