### ISSUE TITLE
eztvapi won't working?

### ISSUE THREAD

**Issue by blackPantherOS** [PopcornTime-CE/desktop#115]
Few days ago the PTCE Series-tab stopped working, page is empty. Before the anime tab displayed API response error message and status.popcorntime.ag does not available as well. The Moovies tab working fine but https://eztvapi.ml/shows.....url still not available 

[29367:1220/235445:INFO:CONSOLE(43)] ""[%cINFO%c] Returning cached provider" "color: blue;" "color: black;" "TVApi"", source: app://host/src/app/app.js (43)
[29367:1220/235445:INFO:CONSOLE(43)] ""[%cINFO%c] Request to TVApi" "color: blue;" "color: black;" "https://eztvapi.ml/shows/1?sort=seeds&limit=50&genre=All&order=-1"", source: app://host/src/app/app.js (43)

Any idea?

**Comment by YIFYtorrents** [comment]
there's a new update with fixed TV API https://github.com/PopcornTimeCommunity/desktop/commit/4bb5c206cd76ee7049ae1491ae370eee47c92321

**Comment by blackPantherOS** [comment]
Thank You! The series not working fine again,It was important for me :) 
Anime tab still does not work. I saw in butter-project has implemented the multilang-movie support, maybe you plan this?

**Comment by YIFYtorrents** [comment]
>Thank You! The series *not* working fine again,It was important for me :)

Does TV series it work or not. I am bit confused because of your smiley at the end.

>I saw in butter-project has implemented the multilang-movie support, maybe you plan this?

I was thinking about adding some german movies from http://video2k.is via google cloud player

**Comment by blackPantherOS** [comment]
Work, I can confirm. 
I'm so sorry, This predict problem maybe or I'm was careless, I don't know what happend :)

**Comment by YIFYtorrents** [comment]
your're welcome
