### ISSUE TITLE
Clicking on movie covers does nothing. Series works Ok.

### ISSUE THREAD

**Issue by MarioMey** [PopcornTime-CE/desktop#141]
I was on Ubuntu-Mate 16.04 and, some day, clicking in movie covers stopped working. I don't remember if it was after an update, sorry. I installed it again, removed .config/PopcornTime folder... but nothing changed.

Now, I've installed Debian 9 (Mate) and PopcornTime has the same behaviour as Ubuntu.

I click in any Serie cover and it works Ok: I can watch any episode of any season of any serie.

Pasting (Ctrl-V) a magnet link works ok. It's the only workaround for watching a movie using PopcornTime.

**Comment by orsolli** [comment]
Change the API Endpoint in settings.
New API Endpoints:
movie http://yify.is/api/v2/list_movies.json
movie http://yts.ph/api/v2/list_movies.json

Source: https://www.reddit.com/r/PopcornTimeCE/comments/3vn6bs/ultimate_tutorial_download_ptce_original_binaries/

**Comment by MarioMey** [comment]
Yes, man. It worked. Thanks.
