### ISSUE TITLE
Movie sources merge

### ISSUE THREAD

**Issue by DotTheI** [PopcornTime-CE/desktop#15]
PTCE 0.3.8.5 uses YTS as a source for movies. Some of the movies from that source are not present in the source used in v. 0.3.8.9. It forces users to have two versions of PTCE installed on their devices. It would be really cool to merge the sources in the upcoming version. Meanwhile, perhaps, anyone can explain how to add a second source into PTCE manually?

**Comment by YIFYtorrents** [comment]
You don't need to have two versions. v3.9 has an option to change sources / API and next version will merge [video2k](http://video2k.is) and [yify.is](http://yify.is) together. Meanwhile you can check out this tutorial: 

https://www.reddit.com/r/PopcornTimeCE/comments/3ynqyd/switching_to_ytsag_api_with_gui_newfeature_bugfix/

**Comment by DotTheI** [comment]
@YIFYtorrents Thank you! Wondering, why yts.ag is not going to be included in the next version?

**Comment by YIFYtorrents** [comment]
Check out [official download](https://www.reddit.com/r/PopcornTimeCE/comments/3xa881/downloads/) post at reddit. There you'll find a link on how to change API to yts.ag if desired. We treat all APIs equally and it's your choice, which one to use.

**Comment by DotTheI** [comment]
@YIFYtorrents I am referring to this: "next version will merge video2k and yify.is together". Why you are going to include video2k.is, but not yts.ag?

**Comment by YIFYtorrents** [comment]
We wouldn't be able to implement 'Google Cloud Player', without video2k.is. It has many advantages compared to other APIs.

**Comment by DotTheI** [comment]
@YIFYtorrents sorry, for not being clear. I am not suggesting to drop video2k.is. I am just asking whether yts.ag will be included as well and, if not, why?

**Comment by YIFYtorrents** [comment]
We don't see any advantage using yts.ag over [yify.is](http://yify.is) and from a technical perspective it wouldn't make any sense to merge sources, because it would create duplicated content. Both have almost same movies.

**Comment by DotTheI** [comment]
**YIFY** Merry Christmas Eve 0.3.9:
![2016-02-19 10 45 03](https://cloud.githubusercontent.com/assets/10737439/13169360/e8adf074-d6f5-11e5-839f-85f00e866c6a.png)
**YTS** There's nothing on TV 0.3.8.5:
![2016-02-19 10 44 41](https://cloud.githubusercontent.com/assets/10737439/13169361/ea370372-d6f5-11e5-8db9-ace8b0404c9d.png)
**YTS** There's nothing on TV 0.3.9:
![2016-02-19 10 49 55](https://cloud.githubusercontent.com/assets/10737439/13169485/f2b3e302-d6f6-11e5-84c3-dea65f2b25c7.png)

**Comment by YIFYtorrents** [comment]
wow, so many different versions

**Comment by DotTheI** [comment]
Indeed. The main difference is in the available resolutions/size. Note that the second and the third one offer different resolutions/sizes while having the same source, YTS
