### ISSUE TITLE
add support for Daum potplayer

### ISSUE THREAD

**Issue by raphcool12** [PopcornTime-CE/desktop#22]
HI, I know we can use other player like VLC kmplayer and many other But a new player is out now and its much better than VLC because is interface is more simple and he dont crash at all I have that player on my PC but but for now Popcorn  time don't detect it so I install VLC too 

but adding support for this new player would be very nice

here is the player website below

https://potplayer.daum.net/
thanks in Advance :)

**Comment by YIFYtorrents** [comment]
not really intersted, vlc is pretty known and stable.
