### ISSUE TITLE
Fix Kat (kick ass torrent) search engine in torrent collection

### ISSUE THREAD

**Issue by raphcool12** [PopcornTime-CE/desktop#24]
Hi, today I want to made a search with the kat search engine my search failed could you fix it please the site is stil online so the problem came from popcorn time. I think you should also made a pirate bay search engine because it's the second best webite to search torrent according to torrent freak 

thanks in advance :)

**Comment by raphcool12** [comment]
Update strike search engine only work for the series need to be fix to :(

**Comment by YIFYtorrents** [comment]
Thanks, I will have an eye on it.

**Comment by captainyarr** [comment]
See the pull request #27 for a fix to both Kat and Strike API.  I was able to get both of them working again.

**Comment by raphcool12** [comment]
ok thanks its good to know that its work again :)

**Comment by raphcool12** [comment]
I Just made a try strike work for me with capitain yarr patch but kat search still have problem for me. I Have no faild now but after 2 minute he still found nothing  the circle in the conor stil turn but show nothing need to check that again :(

keep up the good work :)

**Comment by captainyarr** [comment]
Right now Strike site seems to be down so search is not functioning. KAT seems to be working fine at least on my end.

**Comment by raphcool12** [comment]
I've just try again stil the same thing Strick get my search in 1 sec but when I switch to KAT the circle is turning indefinitly :(

**Comment by raphcool12** [comment]
I just try to go on the strike page with Google Chrome Capitain yarr you'are righ the site is down but When I made my search with popcorn the resault only show up when I click on strike logo so I think the tow logo  have been inverse so maybe when we click on strick icon in fact we where searching on KAT?

anyway check that 

thanks in advance :)

**Comment by raphcool12** [comment]
update on the situation when I click on the strike loge it's show failed now so I guest is down for good and the circle on the rigt coner stil turn indifinitly :(

**Comment by YIFYtorrents** [comment]
its fixed, download v4.0

**Comment by raphcool12** [comment]
sorry I forgot to close it :P
