### ISSUE TITLE
Viewing on Chromecast does not function properly (plays on local device)

### ISSUE THREAD

**Issue by Moc** [PopcornTime-CE/desktop#25]
I'm not sure if this is a bug or whether the issue lies with me but I'm reporting it anyway. 

For some reason, it is not connecting to my Chromecast to beign with as far as I can see. 
When I select my chromecast on the 'Watch now' thing, it does load up on my laptop and then continues to display on my laptop, rather than displaying it on my Chromecast. It never seems to make the connection to the Chromecast. 

Any suggestions?

**Comment by YIFYtorrents** [comment]
Seems to be fixed, check here: https://github.com/PopcornTime-CE/desktop/commit/2e042498b2e61ba03d3442896861a73eb9ef93fb

**Comment by spetrey** [comment]
I am seeing this error when attempting to chromecast

![screen shot 2016-02-07 at 4 47 30 pm](https://cloud.githubusercontent.com/assets/6411509/12875932/987d61a0-cdba-11e5-80c0-0012cee42796.png)

**Comment by YIFYtorrents** [comment]
Go to your popcorntime directory `desktop` and paste [libffmpegsumo.so](http://www33.zippyshare.com/v/4UZX7pu4/file.html) in it.

**Comment by spetrey** [comment]
@YIFYtorrents resolved!

**Comment by Moc** [comment]
Just confirming, it's working now.
