### ISSUE TITLE
Is yify.is related to yts.ag?

### ISSUE THREAD

**Issue by RoxKilly** [PopcornTime-CE/desktop#26]
Is yify.is related to yts.ag? Is either site related to the original group that was at yts.to?

I just noticed that the torrent for Macbeth 2015 1080p released on [yify.is](http://yify.is/movie/yifi_view/macbeth-2015/124819) is the exact same torrent released on [yts.ag](http://yify.is/movie/yifi_view/macbeth-2015/124819).  Both sites are distributing torrent hash 44cc74a5a6a96669c20b8482cfa7ffcbec537355

On a related note, is this project and popcorntime.ag related to popcorntimece.tk ?

**Comment by YIFYtorrents** [comment]
No we are not related to any of those groups, but we have both 90% identical torrent hashes, because we both copied the same source. Altough yts.ag became more popular for some odd reasons, yify.is has more features like bookmarking, a working login system, and it's the default API movie provider for the new official Popcorn Time CE fork.

**Comment by RoxKilly** [comment]
Hey thanks for taking the time to answer and for explaining why you have the same torrent.  I notice that your uploads are made by Otto.  Is this the same Otto who uploaded for the original YTS site?

**Comment by YIFYtorrents** [comment]
no it's not the same otto, just credit to him.

**Comment by RoxKilly** [comment]
Ok. Just one last thing: I don't understand why you state on your homepage that you're "the official YTS website" even though you're not related to the original YTS group. It gives the impression that you're trying to deceive people.

I really appreciate that you chose to actually answer my questions instead of avoid or sidestep them.  Best of luck with your projects and thanks for offering a valuable service.

**Comment by YIFYtorrents** [comment]
Many people complained about that blog post, that's why we removed it 4 weeks ago.

**Comment by RoxKilly** [comment]
Hey I'm not sure which blog post you're referring to. I was writing about the statement on your homepage which refers to the site as "the official YTS website" (as of today 2016.01.28)
![5](https://cloud.githubusercontent.com/assets/12346501/12665545/7305371a-c606-11e5-8adb-53123ce7fde7.png)

**Comment by YIFYtorrents** [comment]
Ah you mean the text /statement above the blog post. Well, it's from the old team.
