### ISSUE TITLE
About adding a subtitle..

### ISSUE THREAD

**Issue by dorukarda** [PopcornTime-CE/desktop#28]
Hi, 

I wonder ıf there is a way to load a subtitle from external file?

best regards.

**Comment by YIFYtorrents** [comment]
Next version will have that option as well opensubtitles.org support

**Comment by dorukarda** [comment]
@YIFYtorrents thanks for updating.

**Comment by YIFYtorrents** [comment]
yeah it's already possible. just go to the player, click subtitles and choose `custom` at the very bottom.
