### ISSUE TITLE
Need more Dutch subtitles

### ISSUE THREAD

**Issue by WickedPoison** [PopcornTime-CE/desktop#31]
I found out a lot of movies have just English and Suomi/Greek subtitles. Can something be done to this?

**Comment by YIFYtorrents** [comment]
The next version will have opensubtitles support

**Comment by YIFYtorrents** [comment]
just download the latest v0.4.0-2 and use the built-in kat.cr search. It supports opensubtitles.org

**Comment by Sikatsu** [comment]
> built-in kat.cr search

For this you need to enable TorrentsTime v2?

**Comment by YIFYtorrents** [comment]
The built-in kat.cr search is enabled by default. Torrents Time v2 is just the name of the entire library, which includes the **KAT search function**. 

> Torrents Time v2 (**http://popcorntime.ag/torrents-time.html**) is a new popular streaming library that is built into Popcorn Time CE (**popcorntime.ag**) 
> 
> Read this: 
> - https://getpopcorntime.org/news/popcorn-time-ce-beta-4-0-with-torrents-time-v2-0/
> - https://getpopcorntime.org/news/ptce-online-popcorntime-ch-kat/
> - https://www.reddit.com/r/PopcornTimeCE/comments/45grxb/breaking_news_torrents_time_v2_will_be_open/
> 
> Built-in Features:
> - loading torrents from your browser on any torrent website
> - anti virus scanner
> - history list
> - built-in KAT.cr search 
> - VLC player
> - chromcast, DLNA, airplay
> - automatic subtitle support
> - added download option in settings (disabled by default)
> 
> ---
> 
> **Note:** Torrents Time v1 (**torrents-time.com**) is a different fork, It's made by **popcorn-time.to** team. That version is closed source and  includes Trojan.Downloader.AIGH detected by AVG software and a bunch of other security issues like xss and midm attacks.
> 
> Security Issues:
> - https://www.virustotal.com/en/file/fa444b29fc3327dc36530e0bbadc883ed176bd98e7e63bbe0cb914459fd81a53/analysis/
> - https://blog.andrew.im/post/139084882590/torrents-time-security-issues
> 
> Built-in Features:
> - loading torrents from your browser on participating websites
> - chromcast, DLNA, airplay
> - automatic subtitle support
> 
> ---
> 
> We don't recommend **popcorntimece.ch** (formerly **popcorntimece.tk**) due to security issues as well.
> - https://archive.is/aNzad

**Comment by Sikatsu** [comment]
I just noticed about the kat.cr search, however, is this different then searching YTS.ph?

**Comment by YIFYtorrents** [comment]
kat.cr has a much bigger collection of movies and tv series. YTS.ph is more focused in quality.

**Comment by YIFYtorrents** [comment]
KAT.cr has a much bigger collection of movies / tv series

**Comment by Sikatsu** [comment]
I see. But where do the other movies (yts.ph) import the subtitles from then actually?

**Comment by YIFYtorrents** [comment]
from http://opensubtitles.org

**Comment by Sikatsu** [comment]
Ah
