### ISSUE TITLE
Stuck on "Waiting for subtitle" and movie not starting

### ISSUE THREAD

**Issue by walterfernandes** [PopcornTime-CE/desktop#32]
When I tray to watch any movie with subtitles (any listed subtitle) is showing "Waiting for subtitle" and the movie don't start.

 Issue #13 still occur with me.

thanks

**Comment by YIFYtorrents** [comment]
>Issue #13 still occur with me.

Go to your popcorntime directory desktop and paste [libffmpegsumo.so](http://www33.zippyshare.com/v/4UZX7pu4/file.html) in it.

**Comment by walterfernandes** [comment]
> Go to your popcorntime directory desktop and paste libffmpegsumo.so in it.

I have already done it but still not working, it should be just for Google Cloud player problem?
I can play the movie only on vlc player, Popcorn or Cloud player isn't working.

Thanks

**Comment by captainyarr** [comment]
I was seeing the same issue with the subtitles not downloading correctly when launching a file from the search. Moving from opensubtitles-api to opensubtitles-ce seems to have fixed the issues. I sent over a pull request for this small change.

**Comment by Bicet** [comment]
@captainyarr 
I was having the same issue on mac and i've solved it by copying ffmpegsumo.so (after showing package contents of Popcorn-time) into

Popcorn-Time-CE.app/Contents/Frameworks/nwjs\ Framework.framework/Libraries/

and replacing the file with the one uploaded here: http://www53.zippyshare.com/v/hy48669w/file.html
