### ISSUE TITLE
Strike API no longer in service

### ISSUE THREAD

**Issue by captainyarr** [PopcornTime-CE/desktop#37]
Recently checked and notice the Strike search and api has been taken down, and is no longer being supported.

I think I am going to try and replace it with piratebay search.

**Comment by YIFYtorrents** [comment]
check this https://github.com/PopcornTime-CE/desktop/issues/24 and make sure to apply the bug fix.

**Comment by raphcool12** [comment]
good idea but you should also repair KAT too because these 2 website or the most popular torrent site

note this 2 two icon seems to be invert acording to a guy on reddit when we click on strike icon we are in fact on kat and the kat on strike because since you aply the patch only the strike icon work 

so check that

thanks in advance :)

**Comment by YIFYtorrents** [comment]
I know about the issues but the team is quite busy at the moment, working on a browser version.

**Comment by raphcool12** [comment]
ok it's good to know also we really have to change the tv show api it's really empty :)

**Comment by YIFYtorrents** [comment]
change Endpoint to http://eztvapi.ml and let me know if it has enough tv shows

**Comment by captainyarr** [comment]
I made a small update to the opensubtitles package used that all video to work properly after a KAT search.  I'm not having any issues with KAT searches after this change.

**Comment by raphcool12** [comment]
strange for me Kat search still not working :( and eztvapi.ml seems to be the same content of the default api

**Comment by YIFYtorrents** [comment]
same problem here, the bug fix doesn't seem to work. I applied kat https://github.com/PopcornTime-CE/desktop/issues/24 and opensubtitles https://github.com/PopcornTime-CE/desktop/commit/c69a59c72cfd8aa4913edaaca67a8f37876eef12 patches.

**Comment by raphcool12** [comment]
im glad to see I'M not the only one to have that problem alot of people report having problem with KAT search too I hope you will find a way to fix it :)

**Comment by YIFYtorrents** [comment]
kat search works again, but only the one from the git. I can't figure out what's missing.

EDIT: next version will fix the kat search from source.

**Comment by raphcool12** [comment]
you mean the Kat api here? https://github.com/paulhobbel/kat-api

**Comment by YIFYtorrents** [comment]
new version is coming today and it has fixed kat.cr search

**Comment by YIFYtorrents** [comment]
v4.0 - Changelog on Reddit: https://www.reddit.com/r/PopcornTimeCE/comments/45r3j8/changelog_040_beta_torrents_time_v20_we_put/

v4.0 - Changelog on Github: https://github.com/PopcornTime-CE/desktop/commit/5d635a208491961bb6e6013431eebc5c7cf145dc?short_path=4ac32a7#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

## history

![history](https://cloud.githubusercontent.com/assets/16165181/13034366/5e75e3f8-d32b-11e5-8f74-2fde124c1e01.png)

## search on kat.cr fixed

![search-on-kat](https://cloud.githubusercontent.com/assets/16165181/13034369/5e877f6e-d32b-11e5-8767-e2d895b27909.png)

## new setting options

![settings](https://cloud.githubusercontent.com/assets/16165181/13034368/5e81486a-d32b-11e5-8704-5dbc5df7173f.png)

## stream magnet link from your browser

![stream-magnet-link-from-browser](https://cloud.githubusercontent.com/assets/16165181/13034370/5e882342-d32b-11e5-9614-59b710fdcf1e.png)

## stream torrent link from your browser

![stream-torrent-from-browser](https://cloud.githubusercontent.com/assets/16165181/13034371/5e8a699a-d32b-11e5-99ec-3c76f1c57985.png)

## opensubtitles fixed

![subtitles](https://cloud.githubusercontent.com/assets/16165181/13034372/5e8f6b8e-d32b-11e5-8587-f745f48be7a4.png)

## player

![player](https://cloud.githubusercontent.com/assets/16165181/13034367/5e7e750e-d32b-11e5-8a75-4eefb6994ade.png)

**Comment by raphcool12** [comment]
its work now thank you so mutch :)   I just tested it its amazing becuse now we can stream on any torrent site without turning off adblock you rock guys:) except there is one thing a little weird when I stream something from another website like kat I alerady open popcorn time but it's make him start again just to read the video I select so when I do that have got two popcorn time windows running :)

**Comment by YIFYtorrents** [comment]
thanks for your opinion, this is so much better than the old version. It has built-in FAKE Scanner and VLC Support, has download option any many other feature.

> there is one thing a little weird when I stream something from another website like kat I alerady open popcorn time but it's make him start again just to read the video I select so when I do that have got two popcorn time windows running :)

this version 2.0 opens multiple instances and may cause memory issues, but I assume you have at least 2 GB of RAM, so it should run smoothly. BTW, the fork is already working on a built-in tab solution.

**Comment by raphcool12** [comment]
ok take your time
