### ISSUE TITLE
Absent subtitles

### ISSUE THREAD

**Issue by aurimus** [PopcornTime-CE/desktop#40]
Would be great if subtitles be available in VLC, it might as well be all of the languages (why not?).

I miss this feature from Stremio.

**Comment by aurimus** [comment]
I found  [here](https://github.com/PopcornTime-CE/desktop/blob/master/src/app/lib/device/ext-player.js) that the subtitle file should already be available, any idea why it does not appear in VLC?

**Comment by YIFYtorrents** [comment]
I can stream to VLC with subtitles. Yeah, it works, but you have to choose subtitles before you click the WATCH button

EDIT: new version 4.0 with fixed opensubtitles support: https://www.reddit.com/r/PopcornTimeCE/comments/45r3j8/changelog_040_beta_torrents_time_v20_we_put/

**Comment by aurimus** [comment]
oh, I didn't see it was there! Thanks

**Comment by aurimus** [comment]
It actually does not find subtitles for most popular movies with 4.0

**Comment by YIFYtorrents** [comment]
kat.cr search (torrents time v2) or yify torrents. I mean external torrents or yify ones.

**Comment by aurimus** [comment]
From the regular thumbnail list, there is no choice for language actually, Gladiator movie here

![popcorn-subtitles-lack](https://cloud.githubusercontent.com/assets/1052992/13238581/bbdbb63c-d9dc-11e5-8015-5b64b610f8ab.png)

**Comment by YIFYtorrents** [comment]
just install the latest version v0.4.0-2 from our releases and search for gladiator with the built-in kat.cr search. It will automatically get all subtitles from opensubtitles.org

**Comment by aurimus** [comment]
Most of the movies still have no subtitles even though they are sitting at opensubtitles.org, is it because there is no YIFY tag on those?

v0.4.0-3

**Comment by YIFYtorrents** [comment]
everything works like a charm. Just update your popcorn time to v.4.1-5
