### ISSUE TITLE
Chromecast improvements

### ISSUE THREAD

**Issue by Sikatsu** [PopcornTime-CE/desktop#44]
Currently when I'm casting to the Chromecast, after a while the movie will stop. I can't click on pause/resume neither can I scroll backwards or forwards. Could this system be improved? Maybe that it shows the normal videoplayer when you don't cast to the chromecast? That will also allow custom subtitles for chromecast and a better working videoplayer.

**Comment by YIFYtorrents** [comment]
Chromecast-api is a new fork from chromecast-js with a few fixes and changes in functionality. 
- https://github.com/alxhotel/chromecast-api

**Comment by Sikatsu** [comment]
And how can we change that api?

**Comment by Sikatsu** [comment]
@YIFYtorrents 

And can you make the custom subtitle also work for chromecast? The viewer is currently very basic, neither do I seem to change the subtitle speed for chromecast. :)

**Comment by YIFYtorrents** [comment]
just open up popcorn time and wait for the update 4.1-5 to appear.
