### ISSUE TITLE
Plays random file from torrent with many files

### ISSUE THREAD

**Issue by aurimus** [PopcornTime-CE/desktop#47]
When I paste, for example [this torrent](https://thepiratebay.se/torrent/9131657/Prison_Break_S01_Season_1_720p_BluRay_ReEnc_DeeJayAhmed#filelistContainer) it starts playing random episode, in this case the 2nd. Same with other torrents with many files.. it no longer displays the file list to choose from.

Version 4.0, Ubuntu 14.04

**Comment by YIFYtorrents** [comment]
it actually should play the largest video file. However you can disable autoplay (in settings) to be able to manually choose the file you want to stream and get the file list with its size, etc.

**Comment by aurimus** [comment]
I see, thanks! .. Although it's actually a bit confusing reading the hover explanation, it does not say anything about that.

**Comment by YIFYtorrents** [comment]
check the latest commit: https://github.com/PopcornTimeCommunity/desktop/commit/3583bf32ee2075a79619c2305f599ac5512a00f8
