### ISSUE TITLE
Why No Releases On GitHub?

### ISSUE THREAD

**Issue by ghost** [PopcornTime-CE/desktop#48]
Hi,

I see on popcorntime.ag there is release 4.0.0.

Why aren't releases being placed under the 'releases' here?

https://github.com/PopcornTime-CE/desktop/releases

GitHub is the development platform and the binary and source releases should be placed here...

Hmm

**Comment by YIFYtorrents** [comment]
## [v0.4.0-2](https://github.com/PopcornTime-CE/desktop/releases)
- windows: https://github.com/PopcornTime-CE/desktop/releases/download/v0.4.0-2/popcorn-time-community-v0.4.0-2-win.msi
- linux 32 bit: https://github.com/PopcornTime-CE/desktop/releases/download/v0.4.0-2/popcorn-time-community-v0.4.0-2-32bit.tar.xz
- linux 64 bit: https://github.com/PopcornTime-CE/desktop/releases/download/v0.4.0-2/popcorn-time-community-v0.4.0-2-64bit.tar.xz

**Comment by aurimus** [comment]
Does the auto-updater actually work?

**Comment by YIFYtorrents** [comment]
no it doesn't, it's impossible to hack signatue, checksum and fingerprint

**Comment by ghost** [comment]
Ahhh I see there is now the first release on GitHub!

Congratulations! :)

**Comment by YIFYtorrents** [comment]
>Does the auto-updater actually work?

@aurimus auto updater works like a charm.
