### ISSUE TITLE
Bookmark issue

### ISSUE THREAD

**Issue by Sikatsu** [PopcornTime-CE/desktop#52]
Using the latest version 4.0.2 when I bookmark a movie it works again like it should. However when I want to go back to ''Movies'' the screen will be gray and I need to restart Popcorn Time.

Steps to reproduce:
- Click on the bookmark icon
- Click on any other button (for example Movies)
- The screen will show up like this http://prntscr.com/a7awoc and you need to restart popcorn time.

**Comment by YIFYtorrents** [comment]
this is because you haven't completely uninstalled the settings of the old version. click `settings` and click button `Flush all databases` at the very bottom. Restart and voila.

_ps: which os do you have?_

**Comment by Sikatsu** [comment]
Hmm I did completely uninstall it and delete the popcorn time folder. Then reinstalled popcorntime 4.0.2 so I thought that should do the trick. However, the method you said worked for me, thanks for that!

My OS is windows 10.

**Comment by captainyarr** [comment]
I just made a pull request that addresses this issue. The came back for me even after I flushed the cache. There is an exception that isn't caught that causes the issue.  #64 fixes this issue.

**Comment by captainyarr** [comment]
Alright made a clean commit. See #65 for fix.
