### ISSUE TITLE
Torrentfreak is spreading false information

### ISSUE THREAD

**Issue by Sikatsu** [PopcornTime-CE/desktop#53]
Do you know anything about this? @YIFYtorrents https://i.imgur.com/Ul2bD9A.png

**Comment by Sikatsu** [comment]
Do you know anything about this? @YIFYtorrents https://i.imgur.com/Ul2bD9A.png

**Comment by YIFYtorrents** [comment]
This is propaganda material created by the malicious /r/popcorntime subreddit. I have contacted torrent freak to request removal of it, but it seems they've affilaited with .sh scammers.  They're probably getting paid to promote this very lie. The torrent freak blog cannot be used as reliable source anymore.

**Comment by Sikatsu** [comment]
Was already thinking about that, thanks for your information.

**Comment by YIFYtorrents** [comment]
Our official Statement: http://popcorntime.ag/official-statement.html
