### ISSUE TITLE
trailer foncton acting little weirdly

### ISSUE THREAD

**Issue by raphcool12** [PopcornTime-CE/desktop#55]
Hi, I notice that when I watch trailer it's take more time as usual  before the trailer start it's to freezing on the main video picture for 5 sec. and sometime a couple more sec. when I have watched two or three trailer sometime the player and time freeze for 2 sec and but the audio continue to work and then after 2 sec the buffering bar move forward to catch the sound and the picture rebecome normal  I suggess you to check every file related to trailer it not suppose to freeze during watch trailer

**Comment by YIFYtorrents** [comment]
maybe yo got some issues with your internet connection
