### ISSUE TITLE
Original Popcorn Time Officialy Hijacked By MPAA

### ISSUE THREAD

**Issue by YIFYtorrents** [PopcornTime-CE/desktop#58]
http://popcorntime.ag/official-statement.html

**Comment by konfou** [comment]
> The new popcorn time repository seems to be over at the official popcorn time community edition.

I suppose no one noticed this. The link _popcorn time repository_ has a typo and points to invalid (gith**b**ub.com) url.

**Comment by YIFYtorrents** [comment]
I couldn't find the the typo. Where is the link?
