### ISSUE TITLE
[Feature Request] Open in full screen by default (UI and not the playback) - Mac

### ISSUE THREAD

**Issue by lothar-cell** [PopcornTime-CE/desktop#59]
Once PT is closed in full screen, next time when opened, it should remember it, and open in full screen again. Otherwise it makes no sense to press the full screen button every time, just annoying and eventually you leave it, however PT is best enjoyed in full screen.
I don't mean playback, but the user interface.
Some apps do remember it, like Wunderlist, and all Fluid apps eg., even some Apple apps when "Close windows when quitting an app" is unticked in General Settings.
Please implement it in PT, it would be a big step forward in quality.

**Comment by YIFYtorrents** [comment]
shouldn't be too difficult I think. Definetely worth adding to our todo list.

**Comment by YIFYtorrents** [comment]
you can enter fullscreen with a simple shortcut: `ctrl+alt+f`
it's possible to run fullscreen mode when opened: `Mousetrap.trigger('ctrl+alt+f');`

next version will have an automatic fullscreen option in settings

**Comment by lothar-cell** [comment]
Very nice, can't wait!
Also, the latest OS X window frame enables fullscreen with the green button on the left, the arrows on the right are redundant now. It's only aesthetic, yet would be nice to see updated too.

**Comment by lothar-cell** [comment]
Was there any progress in this?

**Comment by lothar-cell** [comment]
Does someone keep this in mind or got forgotten?

**Comment by YIFYtorrents** [comment]
I was ill the last 3 month, but I will have a look at it asap
