### ISSUE TITLE
Connect to Trakt not working

### ISSUE THREAD

**Issue by soredake** [PopcornTime-CE/desktop#60]
After clicking 'Connect To Trakt' it opens this. 
![1456686412](https://cloud.githubusercontent.com/assets/5204968/13381226/57c56b3e-de5f-11e5-929e-75ca60b223ee.png)

**Comment by YIFYtorrents** [comment]
Which version / os are you using?

**Comment by soredake** [comment]
0.4.0-2 / Gentoo 64-bit

**Comment by YIFYtorrents** [comment]
please post content of `src/app/templates/settings-container.tpl` from your downloaded version here.

**Comment by soredake** [comment]
@YIFYtorrents http://sebsauvage.net/paste/?25c0d1b579783152#gBA8iZkMMsLqN0zaAodiEutB3Vh0nkbdkhwJx1CVMMA=

**Comment by vzamanillo** [comment]
The problem is located at **src\app\lib\providers\trakttv.js**

`Line 418: defer.reject('sent back no token');`

![trakt](https://cloud.githubusercontent.com/assets/10209695/14390255/79dba4ba-fdb6-11e5-8da2-93963b4efd02.png)

**Comment by YIFYtorrents** [comment]
has the issue been fixed? I have created a new issue https://github.com/PopcornTimeCommunity/desktop/issues/119 because I am not able to sync my watchlist on trakt

**Comment by soredake** [comment]
No, my problem is still here, popcorn-time still opens `data:text/html,chromewebdata`

**Comment by captainyarr** [comment]
@soredake  I have been able to get trakt.tv registration working again in my latest build.  Not submitting yet as I chance a few small things, but I am now able to login and register my trakt account again.

**Comment by captainyarr** [comment]
@soredake  Check #127 for fix
