### ISSUE TITLE
Subtitles search by release

### ISSUE THREAD

**Issue by aurimus** [PopcornTime-CE/desktop#73]
When playing custom torrents (pasting magnet link), they often have very specific name that could be matched with one from opensubtitles.org, wonder if it could be possible to use that to take the correct subtitle. 

Currently it still tries to play with subtitle, but often it's with wrong offset, different release etc.

**Comment by YIFYtorrents** [comment]
Interesting feature request, but in 90 % of cases, it will fetch the right subtitles. However, you can manually add subtitles if necessary.

**Comment by aurimus** [comment]
Well, what I mean basically is that I go manually to OpenSubtitles and download the right subtitles, while the auto subtitles also gets them from opensubtitles, but completely misses the correct one.

Basic formula for criteria:
1. Same type of release (BluRay, Scr, web-dl, etc.)
2. Same release (brand) or simply most downloads.
