### ISSUE TITLE
Years Showing Up As Boxes...

### ISSUE THREAD

**Issue by ghost** [PopcornTime-CE/desktop#8]
I just noticed in the latest source that the `Year` on a lot shows is showing up as a box, please look at the screen shot below;

![popce](https://cloud.githubusercontent.com/assets/13072581/12029573/0aa88db2-ade6-11e5-8127-0ec77b8a12e8.jpg)

**Comment by YIFYtorrents** [comment]
Ohh, I forgot to upload some player icons.

Here is the missing icons ![googlecloud-favicon](https://cloud.githubusercontent.com/assets/16165181/12032879/fe14a2aa-ae14-11e5-888a-066f2e3c5193.png) ![external-vlc-icon](https://cloud.githubusercontent.com/assets/16165181/12032905/5fe543f4-ae15-11e5-92b0-9e0ca5072d4d.png) ![local-icon](https://cloud.githubusercontent.com/assets/16165181/12032911/6c4c2f2c-ae15-11e5-847b-08c3f0052866.png)

I am pretty new to github. How is it possible to add those icons to the repo? Could you create a pull request?

**Comment by ghost** [comment]
If you're talking about the player icons as this problem, the problem is the year, not icons.

Unless you mean, the icons as a separate issue?

I'm not new to github, but I never really learned a lot about it either...

Sorry can't really help out much for github, and a pull request, not even sure how to make it, when I looked at it.

Git certainly has a hell of a lot of crap to it LOL...

**Comment by ghost** [comment]
I found this about adding something from the CLI;

https://help.github.com/articles/adding-a-file-to-a-repository-from-the-command-line/

**Comment by YIFYtorrents** [comment]
The icons are located in the year div container. It affects also the year style.

**Comment by ghost** [comment]
ahhh ok

**Comment by captainyarr** [comment]
I noticed this fix hasn't been merged into the main repo. I'll create a pull request labelled "add_icons"
