### ISSUE TITLE
eztvapi.ml is down ?

### ISSUE THREAD

**Issue by pRieStaKos** [PopcornTime-CE/desktop#86]
Today i notice that PTC is not loading TV Shows. I went to http://eztvapi.ml/ and says is down

```
This site can’t be reached

eztvapi.ml’s server DNS address could not be found.
Did you mean http://getapk.ml/?
Search Google for eztvapi ml
ERR_NAME_NOT_RESOLVED
```

Any update on the TV Shows API ?

**Comment by Lksreis** [comment]
Hi i try http://eztvapi.ml/ API today and works fine.
But i change to https://api-fetch.website/tv/

**Comment by pRieStaKos** [comment]
@Lksreis thank you. I change it back to eztvapi.ml and it's ok. 

Thank you
