### ISSUE TITLE
[UI] output popup inconsistency 

### ISSUE THREAD

**Issue by xymor** [PopcornTime-CE/desktop#87]
The items inside the watch popup should be output mediums, where the content will be sent. 
Items such as Google Cloud and other sources should be with the other source input choices, currently the resolutions. 

![photo_2016-06-07_22-35-16](https://cloud.githubusercontent.com/assets/33407/15880080/4fdeefe0-2d00-11e6-8bf8-873a9f91ab99.jpg)

**Comment by YIFYtorrents** [comment]
thanks for reminding. Will have a look at it.
