### ISSUE TITLE
TV API Is URL...

### ISSUE THREAD

**Issue by ghost** [PopcornTime-CE/desktop#9]
This was discussed before, don't know if that was with the .ml repo or YIFY, but the issue, whoever it was with was removed.

When you click on the TV section it changes to an URL, this is not the correct place to have an URL. an URL is to click and visit a site, in this situation this URL is only telling us who the API is, which should just show a name instead.

Please place the URL in the preferences section, it is more professional being placed in preferences and placing a name on the GUI. 

An URL serves no purpose on a GUI and is not professional design, this looks unprofesional now...

![popurl](https://cloud.githubusercontent.com/assets/13072581/12029597/ac6ddd82-ade6-11e5-9d33-8217a0f2e375.jpg)

**Comment by YIFYtorrents** [comment]
I am going to change it. Thanks for the good vibes.

EDIT: I changed my opinion. #9 (comment) I think the url onclicked is important. The user should always know where the source is coming from. It's for transparency & legal reasons. People should know that we are only linking to third party content. It's not popcorn time content. I think we are not interested in hiding it anymore.

**Comment by ghost** [comment]
I try... :)
