### ISSUE TITLE
Kat is down. Change Torrent search source

### ISSUE THREAD

**Issue by pRieStaKos** [PopcornTime-CE/desktop#96]
So kat.cr is down. Its time to change the "Movie/TV Series search" source.

But what's the alternative ?

**Comment by YIFYtorrents** [comment]
gonna change to rarbg soon

**Comment by pRieStaKos** [comment]
Good thinking


## 

/pR

**Comment by pRieStaKos** [comment]
Since there is not update on this, I'm replying to update this issues.

I'm watching the KAT news, as members have released **_kickass.cd_** (for now).

**Comment by YIFYtorrents** [comment]
there are so many copycats around.

http://kickasstorrents.to 

http://kickass.cd

http://katcr.co (made by old members)

https://kat.how/ (made by isohunt)

**Comment by YIFYtorrents** [comment]
@pRieStaKos i have just added rarbg.to API

**Comment by pRieStaKos** [comment]
I just updated to latest. Nice changes.

Issue is closed.
